name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
         python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: | 
        pytest tests/
    - name: Train model
      run: |
        python src/data/make_dataset.py
        python src/model/train_model.py
    - name: Build Docker image
      run: |
        docker build -t text-classifier .
    - name: Run Docker container
      run: | 
        docker run -d -p 5000:5000 text-classifier
    - name: Test API
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"text": "This is a test"}' http://localhost:5000/predict




        
        
         
